
[2020-05-12 16:40:04] skeletonlog.ERROR: Uncaught Exception Error: "Class 'Kptask\User\Validator\UserValidator' not found" at /vagrant/kptask/config/bootstrap.php line 189 {"exception":"[object] (Error(code: 0): Class 'Kptask\\User\\Validator\\UserValidator' not found at /vagrant/kptask/config/bootstrap.php:189)"} []
[2020-05-12 16:57:58] skeletonlog.ERROR: Uncaught Exception Error: "Class 'Kptask\User\Validator\UserValidator' not found" at /vagrant/kptask/config/bootstrap.php line 189 {"exception":"[object] (Error(code: 0): Class 'Kptask\\User\\Validator\\UserValidator' not found at /vagrant/kptask/config/bootstrap.php:189)"} []
[2020-05-12 17:00:35] skeletonlog.ALERT: Fatal Error (E_COMPILE_ERROR): Declaration of Kptask\User\Infrastructure\Repository\UserRepository::create(Kptask\User\Domain\Entity\User $userModel) must be compatible with Kptask\Core\Repository\UserRepositoryInterface::create(Kptask\User\Entity\User $user) {"code":64,"message":"Declaration of Kptask\\User\\Infrastructure\\Repository\\UserRepository::create(Kptask\\User\\Domain\\Entity\\User $userModel) must be compatible with Kptask\\Core\\Repository\\UserRepositoryInterface::create(Kptask\\User\\Entity\\User $user)","file":"/vagrant/kptask/src/User/src/Infrastructure/Repository/UserRepository.php","line":15,"trace":null} []
[2020-05-12 17:13:14] skeletonlog.ERROR: Uncaught Exception TypeError: "Argument 2 passed to Kptask\User\Domain\Validator\UserValidator::__construct() must be an instance of Kptask\Core\Repository\UserRepositoryInterface, instance of Kptask\User\Infrastructure\Repository\UserRepository given, called in /vagrant/kptask/config/bootstrap.php on line 189" at /vagrant/kptask/src/User/src/Domain/Validator/UserValidator.php line 32 {"exception":"[object] (TypeError(code: 0): Argument 2 passed to Kptask\\User\\Domain\\Validator\\UserValidator::__construct() must be an instance of Kptask\\Core\\Repository\\UserRepositoryInterface, instance of Kptask\\User\\Infrastructure\\Repository\\UserRepository given, called in /vagrant/kptask/config/bootstrap.php on line 189 at /vagrant/kptask/src/User/src/Domain/Validator/UserValidator.php:32)"} []
[2020-05-12 17:14:42] skeletonlog.ERROR: Uncaught Exception TypeError: "Argument 1 passed to Kptask\User\Domain\Validator\UserValidationManager::__construct() must be an instance of Kptask\Core\Repository\UserRepositoryInterface, instance of Kptask\User\Infrastructure\Repository\UserRepository given, called in /vagrant/kptask/config/bootstrap.php on line 194" at /vagrant/kptask/src/User/src/Domain/Validator/UserValidationManager.php line 36 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to Kptask\\User\\Domain\\Validator\\UserValidationManager::__construct() must be an instance of Kptask\\Core\\Repository\\UserRepositoryInterface, instance of Kptask\\User\\Infrastructure\\Repository\\UserRepository given, called in /vagrant/kptask/config/bootstrap.php on line 194 at /vagrant/kptask/src/User/src/Domain/Validator/UserValidationManager.php:36)"} []
[2020-05-12 17:25:46] skeletonlog.ERROR: Uncaught Exception Error: "Class 'Kptask\User\Validator\EmailValidator' not found" at /vagrant/kptask/src/User/src/Domain/Validator/UserValidationManager.php line 52 {"exception":"[object] (Error(code: 0): Class 'Kptask\\User\\Validator\\EmailValidator' not found at /vagrant/kptask/src/User/src/Domain/Validator/UserValidationManager.php:52)"} []
[2020-05-12 17:29:02] skeletonlog.ERROR: Uncaught Exception Error: "Class 'Kptask\User\Entity\User' not found" at /vagrant/kptask/src/Core/src/Factory/AbstractDomainFactory.php line 22 {"exception":"[object] (Error(code: 0): Class 'Kptask\\User\\Entity\\User' not found at /vagrant/kptask/src/Core/src/Factory/AbstractDomainFactory.php:22)"} []
[2020-05-14 15:24:38] skeletonlog.ALERT: Fatal Error (E_ERROR): Interface 'Kptask\Core\Service\UserServiceInterface' not found {"code":1,"message":"Interface 'Kptask\\Core\\Service\\UserServiceInterface' not found","file":"/vagrant/kptask/src/User/src/Domain/Service/UserService.php","line":18,"trace":null} []
[2020-05-14 16:01:45] skeletonlog.ERROR: Uncaught Exception TypeError: "Argument 1 passed to Kptask\User\Infrastructure\Repository\UserRepository::__construct() must be an instance of Kptask\Core\Mapper\UserMapperInterface, instance of Kptask\User\Infrastructure\Mapper\UserDbAdapter given, called in /vagrant/kptask/config/bootstrap.php on line 185" at /vagrant/kptask/src/User/src/Infrastructure/Repository/UserRepository.php line 35 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to Kptask\\User\\Infrastructure\\Repository\\UserRepository::__construct() must be an instance of Kptask\\Core\\Mapper\\UserMapperInterface, instance of Kptask\\User\\Infrastructure\\Mapper\\UserDbAdapter given, called in /vagrant/kptask/config/bootstrap.php on line 185 at /vagrant/kptask/src/User/src/Infrastructure/Repository/UserRepository.php:35)"} []
[2020-05-14 16:20:19] skeletonlog.ERROR: Unable to find template "/usercrud/index.twig" (looked into: /vagrant/kptask/config/../themes/default). [] []
[2020-05-14 16:20:19] skeletonlog.ERROR: #0 /vagrant/kptask/vendor/twig/twig/src/Loader/FilesystemLoader.php(150): Twig\Loader\FilesystemLoader->findTemplate('/usercrud/index...') #1 /vagrant/kptask/vendor/twig/twig/src/Environment.php(299): Twig\Loader\FilesystemLoader->getCacheKey('/usercrud/index...') #2 /vagrant/kptask/vendor/twig/twig/src/Environment.php(381): Twig\Environment->getTemplateClass('/usercrud/index...') #3 /vagrant/kptask/vendor/twig/twig/src/Environment.php(359): Twig\Environment->loadTemplate('/usercrud/index...') #4 /vagrant/kptask/vendor/twig/twig/src/Environment.php(318): Twig\Environment->load('/usercrud/index...') #5 /vagrant/kptask/src/Core/src/Web/AbstractBaseController.php(127): Twig\Environment->render('/usercrud/index...', Array) #6 /vagrant/kptask/src/User/src/Web/UserCrudController.php(79): Kptask\Core\Web\AbstractBaseController->render('index', Array) #7 /vagrant/kptask/src/Core/src/Web/AbstractBaseController.php(90): Kptask\User\Web\UserCrudController->index() #8 /vagrant/kptask/src/Core/src/Middleware/AuthMiddleware.php(72): Kptask\Core\Web\AbstractBaseController->__invoke(Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response)) #9 [internal function]: Kptask\Core\Middleware\AuthMiddleware->__invoke(Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Object(Kptask\User\Web\UserCrudController)) #10 /vagrant/kptask/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array(Object(Kptask\Core\Middleware\AuthMiddleware), Array) #11 /vagrant/kptask/vendor/php-di/php-di/src/DI/Container.php(256): Invoker\Invoker->call(Object(Kptask\Core\Middleware\AuthMiddleware), Array) #12 /vagrant/kptask/src/Core/src/App/WebSkeletor.php(93): DI\Container->call('Kptask\\Core\\Mid...', Array) #13 /vagrant/kptask/src/Core/src/App/WebSkeletor.php(43): Kptask\Core\App\WebSkeletor->handle() #14 /vagrant/kptask/public/index.php(32): Kptask\Core\App\WebSkeletor->__construct(Object(DI\Container), Object(Monolog\Logger)) #15 {main} [] []
[2020-05-14 16:21:26] skeletonlog.ERROR: No entry or class found for 'Kptask\User\Web\Controller\LoginController' [] []
[2020-05-14 16:21:26] skeletonlog.ERROR: #0 /vagrant/kptask/src/Core/src/App/WebSkeletor.php(90): DI\Container->get('Kptask\\User\\Web...') #1 /vagrant/kptask/src/Core/src/App/WebSkeletor.php(43): Kptask\Core\App\WebSkeletor->handle() #2 /vagrant/kptask/public/index.php(32): Kptask\Core\App\WebSkeletor->__construct(Object(DI\Container), Object(Monolog\Logger)) #3 {main} [] []
[2020-05-14 16:22:28] skeletonlog.ERROR: No entry or class found for 'Kptask\User\Web\Controller\LoginController' [] []
[2020-05-14 16:22:28] skeletonlog.ERROR: #0 /vagrant/kptask/src/Core/src/App/WebSkeletor.php(90): DI\Container->get('Kptask\\User\\Web...') #1 /vagrant/kptask/src/Core/src/App/WebSkeletor.php(43): Kptask\Core\App\WebSkeletor->handle() #2 /vagrant/kptask/public/index.php(32): Kptask\Core\App\WebSkeletor->__construct(Object(DI\Container), Object(Monolog\Logger)) #3 {main} [] []
[2020-05-14 16:26:54] skeletonlog.ERROR: No entry or class found for 'Kptask\User\Web\Controller\LoginController' [] []
[2020-05-14 16:26:54] skeletonlog.ERROR: #0 /vagrant/kptask/src/Core/src/App/WebSkeletor.php(90): DI\Container->get('Kptask\\User\\Web...') #1 /vagrant/kptask/src/Core/src/App/WebSkeletor.php(43): Kptask\Core\App\WebSkeletor->handle() #2 /vagrant/kptask/public/index.php(32): Kptask\Core\App\WebSkeletor->__construct(Object(DI\Container), Object(Monolog\Logger)) #3 {main} [] []
[2020-05-14 16:27:26] skeletonlog.ERROR: No entry or class found for 'Kptask\Core\Controller\IndexController' [] []
[2020-05-14 16:27:26] skeletonlog.ERROR: #0 /vagrant/kptask/src/Core/src/App/WebSkeletor.php(90): DI\Container->get('Kptask\\Core\\Con...') #1 /vagrant/kptask/src/Core/src/App/WebSkeletor.php(43): Kptask\Core\App\WebSkeletor->handle() #2 /vagrant/kptask/public/index.php(32): Kptask\Core\App\WebSkeletor->__construct(Object(DI\Container), Object(Monolog\Logger)) #3 {main} [] []
